#!/usr/bin/env python

import json

inventory = { "servers"   : {
        "hosts"   : [ "xyz.blue.com", "xyz.green.com" ]
    },
    "_meta" : {
       "hostvars" : {
          "xyz.green.com" : { "bg_state" : "green", "svc_status" : "active" },
          "xyz.blue.com" : { "bg_state" : "blue", "svc_status" : "inactive" }
       }
    }
}

print(json.dumps(inventory, sort_keys=True, indent=2))
